### model
model_name_or_path: ./LLM-models-datasets/Qwen2.5-3B  # 使用指定的Qwen2.5-3B模型
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all

### dataset
dataset: sky_t1_data_17k  # 使用Sky-T1数据集
template: qwen  # 针对Qwen模型使用qwen模板
cutoff_len: 4096  # 适合长思维链对话数据的序列长度  
max_samples: 16401  # Sky-T1数据集的实际大小
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/qwen2.5-3b-sky-t1/lora/sft  # 更新输出目录以反映Qwen2.5-3B模型
logging_dir: logs/qwen2.5-3b-sky-t1/lora/sft  # 更新日志输出目录以反映Qwen2.5-3B模型
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: tensorboard  # 使用tensorboard记录训练过程
logging_first_step: true  # 记录第一步
logging_nan_inf_filter: true  # 过滤NaN和Inf值
log_level: info  # 日志级别

### train
per_device_train_batch_size: 1  # 因为Sky-T1数据包含长思维链，适当减小batch size
gradient_accumulation_steps: 8  # 增加梯度累积步数以保持有效batch size
learning_rate: 3.0e-5  # 使用稍小的学习率进行精细调优
num_train_epochs: 2.0  # 因为数据量较大，减少epoch数
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true  # Qwen2.5支持bf16，提升训练效率
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
val_size: 0.05  # 使用5%数据作为验证集（数据量大，验证集可以小一些）
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 100  # 增加评估间隔
eval_on_start: false

### 针对Qwen模型和思维链数据优化
use_fast_tokenizer: false  # Qwen模型推荐设置 